site_name: Toshihiko
site_description: Yet another simple ORM for Node.js.
repo_name: toshihikojs/Toshihiko
repo_url: https://github.com/toshihikojs/Toshihiko
edit_uri: edit/v2/docs/

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Models:
      - Definition: model/definition.md
      - Usage: model/usage.md
  - Querying: querying.md
  - Yukari instances: yukari.md
  - Data types: types.md
  - Testing: testing.md
